#!/usr/bin/env python3
"""
AI-Powered Changelog Generator
analyzes images/diffs and appends entries to CHANGELOG.md
"""
import sys
import os
import json
import shutil
import argparse
from datetime import datetime
from pathlib import Path
from typing import List, Literal, Optional
from pydantic import BaseModel, Field

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.append(str(PROJECT_ROOT))

try:
    from config import Config
    from structured_gemini import StructuredGeminiClient
    from google import genai
    from google.genai import types
except ImportError:
    print("❌ Error: Could not import project modules. Run from project root.")
    sys.exit(1)

# ============================================================================
# Schemas
# ============================================================================

class ChangelogEntry(BaseModel):
    """Structured changelog entry generated by AI"""
    title: str = Field(description="Concise, punchy title for the change (e.g., 'Added Dark Mode')")
    type: Literal['Added', 'Changed', 'Deprecated', 'Removed', 'Fixed', 'Security'] = Field(description="Type of change")
    description: str = Field(description="1-2 sentence user-friendly description of what changed")
    image_slug: str = Field(description="Descriptive filename for the image using dashes (e.g., 'dark-mode-ui')")
    tags: List[str] = Field(description="Relevant tags for the change (e.g., 'UI', 'Performance', 'Auth')")

# ============================================================================
# Main Logic
# ============================================================================

class ChangelogGenerator:
    def __init__(self):
        # Load config
        Config.validate()
        self.api_key = Config.GOOGLE_AI_STUDIO_API_KEY
        self.client = StructuredGeminiClient(api_key=self.api_key)
        self.model = "gemini-2.0-flash-exp" # Fast, multimodal model
        
        self.changelog_path = PROJECT_ROOT / "CHANGELOG.md"
        self.assets_dir = PROJECT_ROOT / "assets" / "changelog"
        self.assets_dir.mkdir(parents=True, exist_ok=True)

    def analyze_change(self, image_path: Optional[str], context_text: Optional[str]) -> ChangelogEntry:
        """Generate changelog entry from image and/or text"""
        
        prompt_parts = [
            "You are an expert technical writer managing a software changelog.",
            "Analyze the provided input (screenshot or description) and generate a structured changelog entry.",
            "The content should be user-friendly but accurate.",
            "Focus on the 'Why' and 'What' for the user."
        ]
        
        if context_text:
            prompt_parts.append(f"\nUser context/description: {context_text}")
            
        file_content = None
        if image_path:
            image_path = Path(image_path)
            if not image_path.exists():
                raise FileNotFoundError(f"Image not found: {image_path}")
            
            # Read image for Gemini
            with open(image_path, "rb") as f:
                image_bytes = f.read()
                file_content = types.Part.from_bytes(data=image_bytes, mime_type="image/jpeg" if image_path.suffix in ['.jpg', '.jpeg'] else "image/png")
            prompt_parts.append("\nReference the attached screenshot for UI details.")

        # Construct final prompt
        final_prompt = "\n".join(prompt_parts)
        
        # Determine contents argument based on whether we have an image
        contents = [final_prompt]
        if file_content:
            contents.append(file_content)

        # Generate
        print("🤖 Analyzing change with Gemini...")
        return self.client.generate_structured(
            model=self.model,
            prompt=contents, # prompt arg in generate_structured is mapped to contents
            response_model=ChangelogEntry
        )

    def update_changelog_file(self, entry: ChangelogEntry, final_image_path: Optional[Path]):
        """Append entry to CHANGELOG.md"""
        
        if not self.changelog_path.exists():
            print("Creating CHANGELOG.md...")
            with open(self.changelog_path, 'w') as f:
                f.write("# Changelog\n\n## [Unreleased]\n")

        # Read current content
        with open(self.changelog_path, 'r') as f:
            content = f.read()

        # Format new entry
        image_markdown = ""
        if final_image_path:
            # Use relative path for markdown
            rel_path = final_image_path.relative_to(PROJECT_ROOT).as_posix()
            image_markdown = f"\n  ![{entry.title}]({rel_path})"

        new_entry_md = f"""### {entry.type}
- **{entry.title}**: {entry.description}{image_markdown}
"""
        
        # Insert after "## [Unreleased]"
        if "## [Unreleased]" in content:
            parts = content.split("## [Unreleased]")
            # Look for next header or end
            intro = parts[0] + "## [Unreleased]\n"
            rest = parts[1]
            if rest.startswith("\n"):
                rest = rest[1:] # clean leading newline
                
            new_content = intro + new_entry_md + "\n" + rest
        else:
            # Append if structure logic fails (fallback)
            new_content = content + "\n\n## [Unreleased]\n" + new_entry_md

        with open(self.changelog_path, 'w') as f:
            f.write(new_content)
            
        print(f"✅ Added '{entry.title}' to CHANGELOG.md")

    def run(self, image_path: str = None, context: str = None):
        if not image_path and not context:
            print("❌ Error: Must provide either --image or --context")
            return

        try:
            # 1. Generate Entry info
            entry = self.analyze_change(image_path, context)
            print(f"✨ Generated: {entry.title}")
            
            # 2. Handle Image (Rename & Move)
            final_image_path = None
            if image_path:
                src_path = Path(image_path)
                date_str = datetime.now().strftime("%Y-%m-%d")
                ext = src_path.suffix
                new_filename = f"{date_str}-{entry.image_slug}{ext}"
                final_image_path = self.assets_dir / new_filename
                
                shutil.copy2(src_path, final_image_path)
                print(f"🖼️  Saved image to: {final_image_path}")

            # 3. Update File
            self.update_changelog_file(entry, final_image_path)
            
        except Exception as e:
            print(f"❌ Error: {e}")
            import traceback
            traceback.print_exc()

def main():
    parser = argparse.ArgumentParser(description="AI Changelog Generator")
    parser.add_argument("--image", help="Path to screenshot/image")
    parser.add_argument("--context", help="Text description or diff context")
    args = parser.parse_args()
    
    generator = ChangelogGenerator()
    generator.run(args.image, args.context)

if __name__ == "__main__":
    main()
